import { jaJP } from '@clerk/localizations';
import { ClerkProvider } from '@clerk/nextjs';

import './globals.css';

import { AppWrapper } from './_components/AppWrapper';

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata = {
  title: 'Virtual Credit',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <ClerkProvider
      localization={jaJP}
      appearance={{
        variables: {
          colorPrimary: 'blue',
          colorDanger: 'red',
          colorSuccess: 'green',
          colorWarning: 'yellow',
          colorText: 'black',
          colorTextSecondary: 'gray',
        },
      }}
    >
      <html lang='ja'>
        <body>
          <AppWrapper>{children}</AppWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
